spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybox_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    com:
      mybox: debug
